### ISSUE TITLE
BWG centos8 安装依赖失败

### ISSUE THREAD

**Issue by snuug** [kirin10000/Xray-TLS-Web-setup-script#2]
![image](https://user-images.githubusercontent.com/64509424/100350104-5c465080-3024-11eb-917c-98cde2ae949c.png)

**Comment by kirin10000** [comment]
谢谢反馈，我去检查

**Comment by kirin10000** [comment]
已尝试修复，请检查。因为我的centos8不能复现这个bug，所以只能尝试修复
