### ISSUE TITLE
请问如何在配置中添加Trojan？

### ISSUE THREAD

**Issue by vickunwu** [kirin10000/Xray-TLS-Web-setup-script#3]
另外，Vless加CDN似乎有些问题。

**Comment by kirin10000** [comment]
> 请问如何在配置中添加Trojan？

参考https://www.v2fly.org/config/protocols/trojan.html#inboundconfigurationobject 或者去 v2ray xray仓库提问，这不是本脚本考虑的问题。

> 另外，Vless加CDN似乎有些问题。

Vless加CDN我一直在用呢，请具体说明问题

**Comment by vickunwu** [comment]
Vless似乎不支持 Cloudflare Workers 方式作为 CDN ？
另外请问若使用 Cloudflare DNS 中设置代理  
SSL/TLS 设置 应为灵活还是完全？

**Comment by kirin10000** [comment]
> Vless似乎不支持 Cloudflare Workers 方式作为 CDN ？
> 另外请问若使用 Cloudflare DNS 中设置代理
> SSL/TLS 设置 应为灵活还是完全？

我用的就是Cloudflare DNS处点亮云朵
![image](https://user-images.githubusercontent.com/57820613/100373288-83614a00-3045-11eb-97c0-ae66c06ba508.png)
TLS如下设置
![image](https://user-images.githubusercontent.com/57820613/100373325-9411c000-3045-11eb-8741-e219f770c741.png)
即可使用cdn

注意tcp协议不支持cdn ，只有websocket支持

**Comment by vickunwu** [comment]
好的 我测试一下是否是TLS设置问题
